import { UserProps } from "@/types/user";
import { CATEGORIES } from "./constants";

export const getDefaultBills = (createdUser: UserProps) => {
  return [
    {
      description: "Electricity Bill",
      amount: 100,
      recurrenceDay: 2,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.BILLS,
      userId: createdUser.id,
      contactName: "Power Utilities Co.",
      contactAvatar: "./assets/images/avatars/aqua-flow-utilities.jpg",
      type: "expense",
    },
    {
      description: "Streaming Subscription",
      amount: 30,
      recurrenceDay: 3,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.ENTERTAINMENT,
      userId: createdUser.id,
      contactName: "StreamFlix",
      contactAvatar: "./assets/images/avatars/pixel-playground.jpg",
      type: "expense",
    },
    {
      description: "Internet Bill",
      amount: 100,
      recurrenceDay: 30,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.BILLS,
      userId: createdUser.id,
      contactName: "FastNet Internet",
      contactAvatar: "./assets/images/avatars/urban-services-hub.jpg",
      type: "expense",
    },
    {
      description: "Gym Membership",
      amount: 10,
      recurrenceDay: 11,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.LIFESTYLE,
      userId: createdUser.id,
      contactName: "FitLife Gym",
      contactAvatar: "./assets/images/avatars/serenity-spa-and-wellness.jpg",
      type: "expense",
    },
    {
      description: "Music Streaming",
      amount: 49.99,
      recurrenceDay: 23,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.ENTERTAINMENT,
      userId: createdUser.id,
      contactName: "MusicStream Pro",
      contactAvatar: "./assets/images/avatars/flavor-fiesta.jpg",
      type: "expense",
    },
    {
      description: "Phone Bill",
      amount: 35,
      recurrenceDay: 29,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.BILLS,
      userId: createdUser.id,
      contactName: "Mobile Connect",
      contactAvatar: "./assets/images/avatars/technova-innovations.jpg",
      type: "expense",
    },
    {
      description: "Cloud Storage",
      amount: 50,
      recurrenceDay: 4,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.GENERAL,
      userId: createdUser.id,
      contactName: "CloudTech Solutions",
      contactAvatar: "./assets/images/avatars/bytewise.jpg",
      type: "expense",
    },
    {
      description: "Online Learning Platform",
      amount: 9.99,
      recurrenceDay: 21,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.EDUCATION,
      userId: createdUser.id,
      contactName: "LearnHub Academy",
      contactAvatar: "./assets/images/avatars/elevate-education.jpg",
      type: "expense",
    },
    {
      description: "Monthly Salary",
      amount: 3500,
      recurrenceDay: 1,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.GENERAL,
      userId: createdUser.id,
      contactName: "Tech Company Inc.",
      contactAvatar: "./assets/images/avatars/technova-innovations.jpg",
      type: "expense",
    },
    {
      description: "Rental Income",
      amount: 1200,
      recurrenceDay: 15,
      recurrenceFrequency: "monthly",
      categoryId: CATEGORIES.GENERAL,
      userId: createdUser.id,
      contactName: "Property Management",
      contactAvatar: "./assets/images/avatars/urban-services-hub.jpg",
      type: "expense",
    },
  ];
};
